config/routes.rb
Rails.application.routes.draw do

  resources :payments
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users

  get 'account', controller: :users, as: :account
  get 'login' => "user_sessions#new", as: :login
  get 'logout' => "user_sessions#destroy", as: :logout

  root 'main#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 
    can :manage, :all if user.role == 'admin'
    can :read, :all if user.role == 'coffeeman'
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :from_user, foreign_key: 'from_user_id', class_name: User

  def self.summ
    out = 0
    all.each{ |payment| out = out + payment.money.to_i }
    out
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :payments, foreign_key: 'user_id'
  has_many :my_payments, foreign_key: 'from_user_id', class_name: Payment

  def fio
    "#{last_name} #{first_name} #{middle_name}"
  end

  def self.roles
    %w{admin coffeeman}
  end

  validates :role, inclusion: { :in => self.roles }
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_user?

  helper_method :current_user_session, :current_user

  private
    def require_user?
      redirect_to(login_path) unless current_user
    end

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.create(payment_params.merge(user_id: current_user.id))
    redirect_to payments_path
  end

  def index
    @payments = Payment.all
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def destroy
    Payment.find(params[:id]).destroy
    redirect_to payments_path
  end

  private
  
  def payment_params
    params.require(:payment).permit(:from_user_id, :money, :description)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_user?, only: [:new, :create]

  def new
    unless current_user
      @user_session = UserSession.new
    else
      redirect_to root_path
    end
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to account_path
    else
      redirect_to login_path
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    render :account
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params.merge(role: 'coffeeman'))
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id]).update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:active, false)
    redirect_to users_path
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :middle_name, :ries_id, :email, :password, :password_confirmation, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, class_name = '')
    class_name = current_page?(link_path) ? "#{class_name} active" : class_name

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/views/layouts/application.html.slim
doctype 5
html(lang="en")
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "coffee_club"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "flatly", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  body
    nav[class="navbar navbar-default"]
      .container-fluid
        .navbar-header
          = link_to 'Кофейный клуб "Бодрячок"', root_path, class: 'navbar-brand'
        - if current_user
          ul[class="nav navbar-nav"]
            = nav_link 'Кофеманы', users_path
            = nav_link 'Движение средств', payments_path
            = nav_link 'Профиль', account_path
            li
              = link_to 'Выход', logout_path
    .col-xs-6.col-sm-2

    .col-xs-6.col-sm-9
    	= yield

    /!
      | Javascripts
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/main/index.html.slim
h1
  | Велцоме

app/views/payments/_form.slim
= form_for @payment, class: 'form' do |f|
  = f.label :money, 'Сумма'
  = f.number_field :money, class: 'form-control'
  = f.label :description, 'Описание'
  = f.text_area :description, class: 'form-control'
  = f.label :description, 'От кого принято(если приход)'
  = f.collection_select(:from_user_id, User.all, :id, :fio, {prompt: 'От кого'}, class: 'form-control')

  br/
  .form-group
    = f.submit 'Добавить операцию', class: 'btn-default form-control'

app/views/payments/index.html.slim
h1
  | Движение средств
- if can?(:create, Payment)
  = link_to 'Новый приход/расход', new_payment_path, class: 'btn btn-default btn-large'
  br/
  br/

table.table.table-bordered.table-hover
  thead
    tr
      th
        | Дата
      th
        | Сумма
      th
        | Описание
      th
        | Дополнительно
      th
        | Действия
  tbody
    - @payments.each do |payment|
      tr
        td
          | #{payment.created_at}
        td
          | #{payment.money} 
        td
          | #{payment.description}
        td
          - if(payment.from_user)
            | Принято от #{payment.from_user.fio}
        td
          = link_to 'Посмотреть', payment_path(payment)
          - if can?(:destroy, payment)
            | &nbsp;
            = link_to 'Удалить', payment_path(payment), method: :delete, data: { confirm: 'Удалить операцию?' }

h2
  | Остаток 
  span.label.label-default
    | #{Payment.summ} р.

app/views/payments/new.html.slim
h1
  | Новый платеж
= render partial: 'form'

app/views/payments/show.html.slim
h1
  | Просмотр платежа

.well
  | Дата: #{@payment.created_at}
.well
  | Сумма: #{@payment.money}
.well
  | Описание: #{@payment.description}
- if @payment.from_user
  .well
    | От кого принято: #{@payment.from_user.fio}
.well
  | Внес платеж: #{@payment.user.fio}

app/views/user_sessions/new.html.slim
h1
  | Вход
= form_for @user_session, class: 'form' do |f|
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.submit 'Войти', class: 'btn-lg btn-default'

app/views/users/_form.html.slim
= form_for @user, class: 'form' do |f|
  = f.label :last_name, 'Фамилия'
  = f.text_field :last_name, class: 'form-control'
  = f.label :first_name, 'Имя'
  = f.text_field :first_name, class: 'form-control'
  = f.label :middle_name, 'Отчество'
  = f.text_field :middle_name, class: 'form-control'
  = f.label :ries_id, 'ID пользователя из РИЕС'
  = f.text_field :ries_id, class: 'form-control'
  = f.label :active, 'Активен'
  = f.check_box :active, class: 'form-control'
  = f.label :email, 'Email(используется как логин)'
  = f.email_field :email, class: 'form-control'
  = f.label :password, 'Пароль'
  = f.password_field :password, class: 'form-control'
  = f.label :password, 'Подтверждение'
  = f.password_field :password_confirmation, class: 'form-control'
  br/
  .form-group
    - if f.object.new_record?
      = f.submit 'Создать кофемана', class: 'btn-default form-control'
    - else
      = f.submit 'Сохранить кофемана', class: 'btn-default form-control'

app/views/users/account.html.slim
h1
  | Аккаунт
.well
  | ФИО: #{@user.fio}
.well
  | Email: #{@user.email}
.well
  | Последний взнос: #{@user.ries_id}

app/views/users/edit.html.slim
h1
  | Редактирование кофемана

= render partial: 'form'

app/views/users/index.html.slim
h1
  | Кофеманы

- if can?(:create, User)
  = link_to 'Добавить кофемана', new_user_path, class: 'btn btn-default btn-large'
  br/
  br/

table.table.table-bordered.table-hover
  thead
    tr
      th
        | ФИО
      th
        | Email
      th
        | RIES ID
      th
        | Дата последнего платежа
      th
        | Дата вступления в клуб
      th
        | Статус
      th
        | Действия
  - @users.each do |user|
    tbody
      tr
        td
          | #{user.fio}
        td
          | #{user.email}
        td
          | #{user.ries_id}
        td
          - if user.my_payments.last
            | #{user.my_payments.last.created_at}
          - else
            | Не платил
        td
          | #{user.created_at}
        td
          | #{user.active? ? 'Активен' : 'Деактивирован' }
        td
          = link_to 'Посмотреть', user_path(user)
          - if can?(:edit, User)
            | &nbsp;
            = link_to 'Редактировать', edit_user_path(user)

app/views/users/new.html.slim
h1
  | Новый кофеман
= render partial: 'form'